### PR TITLE
Update gommand.go

### PR DESCRIPTION
**Pull request by justyntemme**
Fixed issue where ctl+c would not cleanup. Now the program detects interrupt signals. Additional features could be added in the goroutine.

### CODE REVIEW

**Comment by dmitshur** [comment]
This looks like a part of the change. Where is `c` declared?

It also needs to be `gofmt`ed.

**Comment by sno6** [comment]
Thanks, this is looking good i'd just like to move around a few things and then can merge.

**Comment by sno6** [comment]
Sorry, I'm still getting a hang of Github. Could you update the commit to support the new changes then I can merge and move around. Thanks

**Comment by justyntemme** [comment]
@sno6 You and me both. Should be fixed and clean. If there is anything else i need to do for this PR just let me know. Thanks for letting me help, cool project!

**Comment by sno6** [comment]
Hi thanks for the help so far if you could just remove the package strings in the imports so it can compile then i can merge.

**Pull request merged**
